### ISSUE TITLE
Theme is not defined

### ISSUE THREAD

**Issue by adrianjacob** [ben-rogerson/twin.macro#12]
Hi,

As an old user of tailwind.macro, first off let me say I love twin.macro. Thanks for the amazing work on behalf of the community.

I have used Twin successfully on a fresh project and its worked brilliantly. However, I am having issues porting an older/large site from tailwind.macro to twin.macro.

After fixing all the old class names, I get the following on every file during 'Gatsby Develop'.

```
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
/xxxx/src/components/faqs/faq.js: twin.macro: theme is not defined Learn more: https://www.npmjs.com/package/twin.macro
```

I have tried everthing:
- removed cache and public
- reinstalled node modules
- etc

To confirm, i have updated all files to call:
`import tw from "twin.macro"
`
And in package.json I have the following (which works fine in my other smaller project)
```
"babelMacros": {
    "styledComponents": {
      "pure": true
    },
    "twin": {
      "config": "./tailwind.config.js",
      "styled": "styled-components",
      "format": "auto",
      "hasSuggestions": true,
      "debug": false
    }
  }
```

Any ideas at first glance?

Thanks,
A.

**Comment by ben-rogerson** [comment]
Hey Adrian, thanks for the kind words.
I'm on holiday so it makes troubleshooting a little difficult, but at first glance it looks like the theme provider might not be sending the theme through to the FAQ component. You're also operating in a subfolder within components so there could be a path issue going on 🤷‍♂️

Let me know if you solve it! Otherwise posting a reduced test case could be a way forward 👍

**Comment by adrianjacob** [comment]
I think its a non Twin issue as it works fine in all other projects - closing issue :)

**Comment by tofiqquadri** [comment]
@adrianjacob how were you able to solve this error?
