### ISSUE TITLE
Flash of unstyled content with Tailwind and Frontity 

### ISSUE THREAD

**Issue by Bowriverstudio** [ben-rogerson/twin.macro#144]
Hello Ben,

I'm using twin macro and Frontity.  They work fantastic, except there is a flash of unstyled content at the start.

Could you please look at this demo site:  https://fouc.bowriverstudio.vercel.app

Repo: https://github.com/Bowriverstudio/flash-of-unstyled-content-frontity-tailwind 1

Best Regards,
Maurice

**Comment by ben-rogerson** [comment]
hey Maurice, I'm not seeing the flash of unstyled content during testing: (cache is disabled too)

![flashof](https://user-images.githubusercontent.com/21288568/92313476-3dc74f00-f00b-11ea-8b25-f079a25443db.gif)

**Comment by Bowriverstudio** [comment]
Thank you for looking at it:  I made a little video: https://www.awesomescreenshot.com/video/811192?key=58abbf6afa34f6d967ca25f345032a09

The logo and menu shift on loading. 
When I comment out this:

```js
import "twin.macro";
```

In: 
 https://github.com/Bowriverstudio/flash-of-unstyled-content-frontity-tailwind/blob/master/packages/mars-theme/src/components/Header/Header.js

The menu does not shift.

Note, on my development version I removed the logo, and the shifting still occurs.

Thanks for your help,
Maurice

**Comment by ben-rogerson** [comment]
I've taken another look at this and I'm pretty sure this is just a css problem as the styles are there from the start.

It looks like the menu is shifting because it doesn't know the width of the logo before it's loaded. There's also some lazy loading that frontity is doing in the background with the `<Image />` component that could be confusing things.

Try setting the width and disable shrinking on the parent link and there shouldn't be a shift:

```html
<a href="#" tw="w-16 flex-shrink-0">
  <Image src={logo} alt="Logo" tw="h-8 w-auto sm:h-10" />
</a>
```

Also, as Frontity provides `css` and `styled` imports which you can set in your twin config like this:

```js
// package.json

"babelMacros": {
    "twin": {
      "styled": {
        "import": "default",
        "from": "frontity"
      },
      "css": {
        "import": "css",
        "from": "frontity"
      },
    }
},
```

Hope that helps!

**Comment by bowriver** [comment]
Thank you for taking a look at this.  That solve the image issue.  You are correct it is not a twin macro issue.

Cheers,
Maurice
