### ISSUE TITLE
Support for 'group' and 'group-hover'

### ISSUE THREAD

**Issue by adrianjacob** [ben-rogerson/twin.macro#25]
Hi,

Love twin.macro - amazing work!

We have noticed a small issue when trying to use 'group' and 'group-hover' tailwind utilities.

We get the following error message:

```
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
/xxxxx/Appssubmenu.js:
✕ group was not found
```

We tested the above with the following code (taken from tailwind docs)

```
<div css={tw`group`}>
  <p css={tw`group-hover:text-white`}>Create a new project from a variety of starting templates.</p>
</div>
```

Have you or anyone else come across this?

Thanks,
Adrian

**Comment by rbutera** [comment]
You need a container element with className group I think?

**Comment by ben-rogerson** [comment]
That's right:

✓ Good:
`<div className="group">`

✕ Bad
`<div tw="group">`

In Twin, you also have some brand new group states to work with:

```
tw`group-hocus:bg-red-500` // a combination of :hover and :focus`.
tw`group-focus:bg-red-500`
tw`group-active:bg-red-500`
tw`group-visited:bg-red-500`
```

In the latest version of Twin [I improved the feedback](https://github.com/ben-rogerson/twin.macro/commit/fe513e815dcddbdbd5b6768dc2b95b17ea2cd98c#diff-b869e1f14c673fbeb88d4b2cd413f4c2R25) if you try to use `group` like a tailwind class because it's such an easy mistake to make.
