### ISSUE TITLE
The order of col-start-x and col-end-x determines if they work or not.

### ISSUE THREAD

**Issue by 0tt0sson** [ben-rogerson/twin.macro#363]
The order of  `col-start-x` seams to be a important so `grid-column` does not override it.
See reproduction on https://codesandbox.io/s/damp-hill-fx33z

![image](https://user-images.githubusercontent.com/230343/111887053-c66b7280-89d2-11eb-9023-e29ef60b5832.png)

The examples from the tailwind docs https://tailwindcss.com/docs/grid-column#starting-and-ending-lines does not due to this.

```tsx
<div tw="grid grid-cols-6 gap-4">
  <div tw="col-start-2 col-span-4">1</div>
  <div tw="col-start-1 col-end-3">2</div>
  <div tw="col-end-7 col-span-2">3</div>
  <div tw="col-start-1 col-end-7">4</div>
</div>

<div tw="grid grid-cols-6 gap-4">
  <div tw="col-span-4 col-start-2 ">1</div>
  <div tw="col-end-3 col-start-1">2</div>
  <div tw="col-end-7 col-span-2">3</div>
  <div tw="col-start-1 col-end-7">4</div>
</div>

```

Did try it with a mix different setups of styled components, emotion, next.js and cra and its seams to be consistent within them all.

**Comment by ben-rogerson** [comment]
Thanks for sharing this issue 👍 

I found that the ordering matters if these rules are sharing the same selector.
It's because `grid-column` is a [shorthand property](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column) that overwrites `grid-column-end` if it’s defined first and in the same selector.

Tailwind has separate selectors - but you can see that if I define `grid-column-end` before `grid-column` in the same selector, then `grid-column-end` is overwritten:

![tailwind](https://user-images.githubusercontent.com/21288568/111898075-adff6480-8a73-11eb-91bb-284400506854.gif)

These css-in-js libraries only create a single selector, so that's why you noticed the consistent behavior:

![Large GIF (796x306)](https://user-images.githubusercontent.com/21288568/111897804-e56d1180-8a71-11eb-8c22-0ce2b3712470.gif)

Perhaps twin could reorder these `grid-column-start/end` rules so that `grid-column` is always defined first?

**Comment by 0tt0sson** [comment]
> Perhaps twin could reorder these `grid-column-start/end` rules so that `grid-column` is always defined first?

This is what I was thinking about this also, if it does not break anything else it's a great solution to avoid confusion and help with the developer experience.

I tried to make this PR at first but struggled with where and how to put something like this in the code as I've never done anything with a babel macro before.

**Comment by ben-rogerson** [comment]
Yeah true, I'll have to make sure there are no issues that pop up after this update.

All good, it took me a while to figure out all this babel stuff.

For your/my information, [this looks like a good spot](https://github.com/ben-rogerson/twin.macro/blob/4ba3292fee95a2d52946697885c2fdb356f330df/src/getStyleData.js#L51) for the reordering.

**Comment by 0tt0sson** [comment]
> Yeah true, I'll have to make sure there are no issues that pop up after this update.
> 
> All good, it took me a while to figure out all this babel stuff.
> 
> For your/my information, [this looks like a good spot](https://github.com/ben-rogerson/twin.macro/blob/4ba3292fee95a2d52946697885c2fdb356f330df/src/getStyleData.js#L51) for the reordering.

Thank you, that helped me a lot. Made a PR now.

**Comment by lightyen** [comment]
Maybe the `transition` has the same issue:
```jsx
<div tw="duration-1000 transition">Demo</div>
```

**Comment by ben-rogerson** [comment]
> Maybe the `transition` has the same issue

Yeah, it suffers from the same issue because twin deep merges the styles so `transition` ends up overwriting the duration style.

Here are the classes `transition` affects:

```js
transition-xxx;
duration-xxx;
ease-xxx;
delay-xxx
```

I’ll have to add a reordering function for those too.
