### ISSUE TITLE
Support the class strategy from the forms plugin

### ISSUE THREAD

**Issue by jgoux** [ben-rogerson/twin.macro#384]
Hello,

We would like to use the class strategy from https://github.com/tailwindlabs/tailwindcss-forms#using-classes-instead-of-element-selectors but even when configuring it we get a MacroError : 
```
MacroError: /Users/admin/Documents/Code/Clovis-team/clovis-labs/clovis/packages/client/src/design-system/elements/TextField/Input.tsx: 

✕ form-input was not found
```

I'm using twin.macro in the context of stitches, if it can help.

I'm wondering if the issue doesn't come from the fact that `@tailwindcss/forms` produces global styles by default and maybe they should be injected by twin.macro instead of stitches like in the example.

Do you think it would be possible to add `stitches` as a preset like styled-components, emotion and goober?

**Comment by ben-rogerson** [comment]
Hey there, thanks for checking out that stitches example.

It's pretty new so there are a few rough edges still but I'm pretty keen on stitches overall and slowly working towards adding a stitches preset.

I've taken a look at the forms plugin and what happens when it switches to the class strategy...

> I'm wondering if the issue doesn't come from the fact that @tailwindcss/forms produces global styles by default and maybe they should be injected by twin.macro instead of stitches like in the example.

That's right, currently the `<GlobalStyles />` aren't being injected by twin and that's where both the css reset and plugins styles that use `addBase` are added.

When class strategy is enabled, the forms plugin tries to add the styles with `addBase` and currently, these are all turned into global styles which aren't matched by twin.

I'll let you know when I've got a pr up, it might be a few weeks away as I've got a few other tasks on the go 🤞

**Comment by as-zlynn-philipps** [comment]
@ben-rogerson +1 on supporting `addBase`. We are writing a Tailwind config to be consumed by multiple packages in our ecosystem, i.e. use the CSS from our design system with or without React/twin.macro. Right now, we have to maintain a custom `GlobalStyle` separately from `addBase` and it would be nice to eliminate the redundancy.

**Comment by ben-rogerson** [comment]
@as-zlynn-philipps im guessing your team is using stitches + twin here too?

**Comment by as-zlynn-philipps** [comment]
@ben-rogerson nope, Styled Components. From my point of view, the issue is that Twin's `GlobalStyles` just pulls in Tailwind's default preflight styles and doesn't consider `addBase`.

**Comment by ben-rogerson** [comment]
If classes are defined using `addBase` (like the tailwind forms class strategy does) - those classes won't work with the tw import/tw prop. A fix is coming on this.

But for other global styles, `addBase` is only missing if you're using stitches right now.

**Comment by as-zlynn-philipps** [comment]
@ben-rogerson that is not my experience. I'm trying to share a codesandbox to demo the issue, but it seems there is another issue with twin.macro working at all in that environment: https://codesandbox.io/s/focused-brook-h4n1t?file=/src/styles/GlobalStyles.js

**Comment by as-zlynn-philipps** [comment]
Couple of related thoughts:

1. How would twin's `GlobalStyles` work when using a different version of Tailwind, say 1.9.6 [as recommended for IE11 compatibility](https://tailwindcss.com/docs/upgrading-to-v2#support-for-ie-11-has-been-dropped)?
2. I know twin ignores the `corePlugins` part of `tailwind.config.js`, but what if we wanted to disable `preflight` and use our own `addBase`? I'd expect twin's `GlobalStyles` to pull in only the `addBase` under those circumstances.

**Comment by ben-rogerson** [comment]
I pulled that codesandbox demo down, installed postcss `npm i -D postcss` and it started up correctly, correctly displaying the `#c0ffee` background. I tested using both npm and yarn.

> How would twin's GlobalStyles work when using a different version of Tailwind, say 1.9.6 as recommended for IE11 compatibility?

Twin doesn't have IE11 compatibility so I don't recommend using twin if you have that requirement.

> I know twin ignores the corePlugins part of tailwind.config.js, but what if we wanted to disable preflight and use our own addBase? I'd expect twin's GlobalStyles to pull in only the addBase under those circumstances.

During the work that needs to be done for a stitches preset, it's looking likely that I'll be exposing the GlobalStyles data to the user.
This means that the reset styles and the addBase styles will become independently available, rather than being automatically added with the `<GlobalStyles />` import.

**Comment by as-zlynn-philipps** [comment]
@ben-rogerson Thanks for investigating. Those steps worked for me too. They also worked for Tailwind v1.9.6, FWIW. Could be that the project I was having trouble with was missing postcss, but I'm not sure.

> Twin doesn't have IE11 compatibility so I don't recommend using twin if you have that requirement.

Correct me if I'm wrong, but it doesn't seem that Twin inherently lacks IE11 support; rather it's Tailwind v2 and Twin's hard-coding of those base styles. At any rate, looks like being able to disable preflight would meet our use case.

**Comment by ben-rogerson** [comment]
Yes, you're right on the IE support - to be more specific, there's no official IE support in twin mostly because of tailwinds reliance on css variables.
You can get around some of that with `disableColorVariables: true` in your twin config but I'm fairly certain you'll stumble on some more issues. That said, you'll probably find workarounds to each of them.
