### ISSUE TITLE
Setting base css variables containing numbers breaks due to stripped hyphens

### ISSUE THREAD

**Issue by lukesmurray** [ben-rogerson/twin.macro#507]
Setting css variables with a number in their name seems to break. The First hyphen is stripped and if there are other hyphens they are stripped as well.

I can reproduce by adding the following plugin to the tailwind config.  

```js
  plugins: [
    function ({ addBase }) {
      addBase({
        ":root": {
          "--color-pink-900": "#831843",
        },
      });
    },
  ],
```

I expect the root to have a css variable defined on it.
Instead the variable is grayed out.

![image](https://user-images.githubusercontent.com/34020210/129195790-17e95d0a-7abb-41f6-bcf8-d8aa3325ac67.png)

If you look closely you can see the hyphens have been changed.

```css
/* expected */
--color-pink-900: #831843;
/* actual */
-color-pink900: #831843;
```

This might be related to some of the short css syntax.

**Comment by ben-rogerson** [comment]
Thanks for sharing this issue.

I found it's creating the following incorrect css in the `globalStyles` import:

```js
({
  // ...
  ":root": {
    "ColorPink900": "#831843"
  }
});
```

And in the `<GlobalStyles />` import it's also incorrect (as you've found):

```js
`
:root {
	-color-pink900: #831843;
}
`
```

Looks like Twin needs a couple of tweaks in this area, I'll patch it up shortly.

The workaround for now is to define the variable in a separate global definition instead of a tailwind plugin.
