### ISSUE TITLE
Stitches styled components return any type

### ISSUE THREAD

**Issue by redbaron76** [ben-rogerson/twin.macro#537]
All the components created by the **Stitches**'s styled-components implementation return `any` type. So it seems that the Stitches `component's types out-of-the-box` feature is completely lost.

In others `styled` usages (Emotion, Styled-Components, ...) it is possible to type styled component through **generics** like this:

```
interface IStyle {
  green?: boolean;
  purple?: boolean;
...
}

const StyledButton = styled.button<IStyle>((props) => [
  tw`rounded text-xl...
...
```

Isn't it possible to adopt a similar approach using Stitches?
Would it be possible?
Thanks

**Comment by lboecker** [comment]
You're supposed to use variants and then extract the prop type with `React.ComponentPropsWithoutRef` or ` React.ComponentPropsWithRef` if needed.

The reason your component is typed `any` is because [types/twin.d.ts](https://github.com/ben-rogerson/twin.examples/blob/88df17fdeb3267da5c5563352955d834d6a52008/next-stitches-typescript/types/twin.d.ts) from the examples repo is broken right now (at least I think it is). When I tried it `StyledTags` was `any` and that's why the `styled` import from twin was `any` (and that's why the components also ended up being `any`).

**Comment by nibtime** [comment]
Hi @redbaron76 

the `twin.d.ts` is unfortunately broken, as @lboecker mentioned, it uses undefined types (`AnyIfEmpty`, `CreateStyledComponent`, so it becomes `any`.

For typing purposes around Stitches, like variant type extraction consult the following: https://stitches.dev/docs/typescript.

I got the best overall type experience with the following `twin.d.ts`:

```ts
import 'twin.macro'
import { css as cssImport, styled as styledImport } from '@stitches/react'
import { CSS as StitchesCSS } from '@stitches/react'

declare global {
  type CSS = StitchesCSS
}

declare module 'react' {
  // The css prop
  interface HTMLAttributes<T> extends DOMAttributes<T> {
    css?: StitchesCSS
    tw?: string
  }
  // The inline svg css prop
  interface SVGProps<T> extends SVGProps<SVGSVGElement> {
    css?: StitchesCSS
    tw?: string
  }
}

declare module 'twin.macro' {
  // The styled and css imports
  const styled: typeof styledImport
  const css: typeof cssImport
}
```

**Comment by ben-rogerson** [comment]
Check the example for the updated types.
