### ISSUE TITLE
Uncaught MacroError: The macro you imported from "undefined" is being executed outside the context of compilation with babel-plugin-macros. 

### ISSUE THREAD

**Issue by Sepush** [ben-rogerson/twin.macro#620]
I use twin.macro vite pnpm storybook in my project I fail to start
and get the error
![image](https://user-images.githubusercontent.com/39197136/151705790-e78dfb3b-1e9d-4b2e-9c51-ac20fb6eb7e1.png)
```


Uncaught MacroError: The macro you imported from "undefined" is being executed outside the context of compilation with babel-plugin-macros. This indicates that you don't have the babel plugin "babel-plugin-macros" configured correctly. Please see the documentation for how to configure babel-plugin-macros properly: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/user.md
```
I get to the link and change the babelrc to "plugin":["macros"] but still not work

I try https://github.com/facebook/relay/issues/2648#issuecomment-499250143 but still not work

my repo link is https://github.com/sea-design/sea-design

.babelrc file is here
https://github.com/sea-design/sea-design/blob/main/.storybook/.babelrc

**Comment by ben-rogerson** [comment]
That error is because the babel file isn't being read and so babel-plugin-macros isn't being loaded correctly.

Perhaps it's something to do with `storybook-builder-vite`? 
[The docs](https://github.com/eirslett/storybook-builder-vite#readme) state the vite config is read from `viteFinal` in `.storybook/main.js` rather than `vite.config.js`.
This means that you'll need to integrate [this vite config](https://github.com/ben-rogerson/twin.examples/blob/master/vite-emotion-typescript/vite.config.ts) within `viteFinal`. Hopefully that works for you 👍

**Comment by Sepush** [comment]
> That error is because the babel file isn't being read and so babel-plugin-macros isn't being loaded correctly.
> 
> Perhaps it's something to do with `storybook-builder-vite`? [The docs](https://github.com/eirslett/storybook-builder-vite#readme) state the vite config is read from `viteFinal` in `.storybook/main.js` rather than `vite.config.js`. This means that you'll need to integrate [this vite config](https://github.com/ben-rogerson/twin.examples/blob/master/vite-emotion-typescript/vite.config.ts) within `viteFinal`. Hopefully that works for you 👍

I move my babelrc file and vite.config file to main.js.It solve the error,but get some new one.
It may not belong to twin.marco.Thanks for your great help.👍
![image](https://user-images.githubusercontent.com/39197136/151933446-2ec535c4-7043-4774-847d-803371165dbb.png)
