### ISSUE TITLE
[Feature] Support for nested group rules within styled-components

### ISSUE THREAD

**Issue by kevinsperrine** [ben-rogerson/twin.macro#66]
I would like to use nesting of styled-components rules to apply group related styles; however, they get applied to the parent instead of the item they are nested within. I realize this may be a large ask, but I figured I would throw it out there. I've created an example repo here: [https://codesandbox.io/s/priceless-voice-31441?file=/src/App.js](https://codesandbox.io/s/priceless-voice-31441?file=/src/App.js)

```js
const NestedHeading = styled.h1`
  ${tw`text-4xl font-bold leading-loose text-blue-500`}

  > span {
    ${tw`transition group-hover:text-blue-900`}
  }
`;

export default function App() {
  return (
    <div className="App">
      <NestedHeading className="group">
        Nested rules via <span>styled-components</span>
      </NestedHeading>
   </div>
  );
}
```

**Comment by rbutera** [comment]
Hi Kevin,

Thanks for using twin.macro

1) your codesandbox seems to fail to load: `/src/App.js: Error: ENOENT: No such file or directory., '/empty.js'`

2) Could you clarify what your desired behaviour is here? I'm having an issue understanding what the issue is. 

If you want to target the `<span>` directly, why use `group-hover`?

It seems logical, in my opinion, that `group-hover:` means "apply this style to the whole group when any item is hovered" 

As you probably know, CSS does not support parent selectors, so AFAIK you cannot write a CSS rule that affects the parent node when a child is hovered?

**Comment by kevinsperrine** [comment]
@rbutera Weird. I think it's working now, but the hover is two-fold. I added a hover effect to the whole H1 to change the background color, but I also want to target the span separately to change its color, too when the h1 is being hovered hence the group. [https://codesandbox.io/s/priceless-voice-31441](https://codesandbox.io/s/priceless-voice-31441)

**Comment by ben-rogerson** [comment]
Using a combination of `group` and nested css selectors won't work.
I believe this is what's happening.

When you try nesting like this:

```js
const Element = styled.h1`
  span {
    ${tw`group-hover:text-purple-500`}
  }
`;
```

It "builds" the selector as:
```css
.group:hover .group span { ... } 
```

When the correct selector should be: 
```css
.group:hover span { ... }
```

So mixing sub selectors with `group-xxx` classes isn't an option 👎
  
But I've [forked your sandbox](https://codesandbox.io/s/compassionate-dew-04yxo?file=/src/App.js) and added a couple of examples on how you could tackle it.

Also, you need an empty `empty.js` file in your project root to get CodeSandbox to work correctly. No idea why.

---

A side note: Instead of adding 'group' to your jsx, you could add it with styled-components:

```js
const ElementWithGroupClassName = styled.h1.attrs({ className: "group" })`
  ${tw`text-black`}
`;
```

**Comment by kevinsperrine** [comment]
Thanks, @ben-rogerson. I figured it was a long-shot. Thanks for the quick reply, tips, and the fantastic library!
