### ISSUE TITLE
@tailwindcss/typography": "^0.5.2, prose not working at all

### ISSUE THREAD

**Issue by jjrchrds** [ben-rogerson/twin.macro#686]
I've installed tailwindcss/typography, then added the ```tw="prose"``` , but the classes are not being applied. Here's what I see in browser:
<img width="1792" alt="Screen Shot 2022-05-11 at 9 42 15 PM" src="https://user-images.githubusercontent.com/3619684/167975085-0a329a7d-e2f5-47e4-9773-a7763f2dd7bb.png">

Below is my markup:
```<article tw="prose">
        <h1>test</h1>
        <h2>test 2</h2>
        <p>
          Lorem ipsum <a href="#">dolor sit</a> amet consectetur adipisicing
          elit. Quas incidunt totam fugiat cumque! Suscipit obcaecati rerum
          molestias sed quidem excepturi deserunt dolorem iure repellat soluta
          perferendis veritatis quod, mollitia autem.
        </p>
        <p>
          Lorem ipsum <a href="#">dolor sit</a> amet consectetur adipisicing
          elit. Quas incidunt totam fugiat cumque! Suscipit obcaecati rerum
          molestias sed quidem excepturi deserunt dolorem iure repellat soluta
          perferendis veritatis quod, mollitia autem.
        </p>
      </article>
```

below are my dependencies:
``` "dependencies": {
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@sindresorhus/slugify": "^1.1.0",
    "debounce": "^1.2.1",
    "dotenv": "^10.0.0",
    "gatsby": "^4.0.2",
    "gatsby-plugin-emotion": "^7.13.0",
    "gatsby-plugin-gatsby-cloud": "^4.0.0",
    "gatsby-plugin-google-analytics": "^4.0.0",
    "gatsby-plugin-image": "^2.0.0",
    "gatsby-plugin-react-helmet": "^5.0.0",
    "gatsby-plugin-sharp": "^4.0.0",
    "gatsby-plugin-sitemap": "^5.0.0",
    "gatsby-source-filesystem": "^4.0.0",
    "gatsby-source-shopify": "^6.0.0",
    "gatsby-transformer-sharp": "^4.0.0",
    "isomorphic-fetch": "^3.0.0",
    "lodash.debounce": "^4.0.8",
    "lodash.isequal": "^4.5.0",
    "query-string": "^7.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.1.0",
    "shopify-buy": "^2.11.0",
    "tailwindcss": "^3.0.24",
    "twin.macro": "^2.8.2",
    "urql": "^2.0.2"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.2"
  }

**Comment by HynekS** [comment]
Same problem here. My experience:

-   "twin.macro": "2.8.1" + "tailwindcss": "2.2.19" +  @tailwindcss/typography": "0.4.0" : Works fine ✔
-   "twin.macro": "2.8.1" + "tailwindcss": "2.2.19" +  @tailwindcss/typography": "0.5.2" : Broken [❌(see the issue here)](https://github.com/tailwindlabs/tailwindcss/issues/6398) 
-   "twin.macro": "2.8.1" + "tailwindcss": "^3.0.24" +  @tailwindcss/typography": "0.5.2": Broken ❌ [(#686)](https://github.com/ben-rogerson/twin.macro/issues/686)
-   "twin.macro": "^3.0.0-rc.1" + "tailwindcss": "^3.0.24" +  @tailwindcss/typography": "0.5.2": Broken ❌ [(#686 again)](https://github.com/ben-rogerson/twin.macro/issues/686)

There is a chance it could be an issue of compatibility between specific versions of `tailwind` and `@tailwindcss/typography` – haven't tested it without `twin.macro`.

**Comment by arafatamim** [comment]
Same here, using twin.macro 3.0.0-rc.1, Gatsby build fails:
```
ModuleBuildError: Module build failed (from ./node_modules/.pnpm/gatsby@4.14.0_qu5w6m46fpgpgl4vgc6uc6ou6m/node_modules/gatsby/dist/utils/babel-loader
  .js):
  MacroError: /project/src/globalStyles.js:
  ✕ prose-h1 was not found
  Did you mean bg-rose-50?
```

**Comment by ben-rogerson** [comment]
The problems here are all because of the lack of the support for the `addVariant()` function in the tailwindcss plugin API.

The last version of `@tailwindcss/typography` before it started using the unsupported function was `v0.4.1`.

See this diff between `v0.4.1...v0.5.0`:

![image](https://user-images.githubusercontent.com/21288568/168451262-0c2cf1d7-1e2f-46b7-a103-7d349a740db2.png)

I'm going to take another look at supporting `addVariant()` for `twin.macro-rc.2` but the workaround is to downgrade to the "pre-addVariant()" version:

```js
npm i @tailwindcss/typography@0.4.1
```

**Comment by wottpal** [comment]
using the `0.4.1` (with rc-1) unfortunately throws the following for me

```
TypeError: twin.macro: Cannot read properties of undefined (reading '700') Learn more: https://www.npmjs.com/package/twin.macro
    at Array.reduce (<anonymous>)
```

**Comment by vse-volod** [comment]
I've got a pretty hacky solution to this:

1. twin-macro@latest, tailwindcss@latest, but "@tailwindcss/typography": "^0.5.0"
2. run yarn, ensure you have this section in lockfile:
`"@tailwindcss/typography@^0.5.0":
  version "0.5.0"
  resolved "https://registry.yarnpkg.com/@tailwindcss/typography/-/typography-0.5.0.tgz#47886ec46ac41e1211d24fea05301046d9b30906"
  integrity sha512-1p/3C6C+JJziS/ghtG8ACYalbA2SyLJY27Pm33cVTlAoY6VQ7zfm2H64cPxUMBkVIlWXTtWHhZcZJPobMRmQAA==
  dependencies:
    lodash.castarray "^4.4.0"
    lodash.isplainobject "^4.0.6"
    lodash.merge "^4.6.2"
    lodash.uniq "^4.5.0"`
3. in gatsby-browser / _app.js(for nextjs) add this:
`import '@tailwindcss/typography/dist/typography.min.css'`
4. use "className" for prose styles, tw as always for all other

Solution has a lot of drawbacks but at least it works though.

**Comment by ben-rogerson** [comment]
The next version will have support for `@tailwindcss/typography` so the workaround shouldn't be needed for too long

**Comment by vse-volod** [comment]
> The next version will have support for `@tailwindcss/typography` so the workaround shouldn't be needed for too long
thats nice! happy to hear that!

**Comment by ben-rogerson** [comment]
Closing due to the fix made available in the next version (rc-2/v3)

**Comment by nibtime** [comment]
> Closing due to the fix made available in the next version (rc-2/v3)

Just upgraded a project to twin.macro@rc and encountered this. Awesome!

**Comment by ben-rogerson** [comment]
Just released `rc.2` with typography support!
Help test the candidate → https://github.com/ben-rogerson/twin.macro/discussions/679

**Comment by wottpal** [comment]
Can confirm the typography plugin is working for me now ❤️

**Comment by nibtime** [comment]
I updated to rc2 and can also confirm that it is working with the latest
version of the typography plugin (0.5.2).

Am Mi., 1. Juni 2022 um 11:35 Uhr schrieb Dennis Zoma <
***@***.***>:

**Comment by Yalchin403** [comment]
if you are using simple html with cdns you can use below combination:

```html
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@tailwindcss/typography@0.4.0/dist/typography.min.css" rel="stylesheet">
```
