### ISSUE TITLE
Doesn't work with CodeSandbox React template

### ISSUE THREAD

**Issue by adamerose** [ben-rogerson/twin.macro#825]
What steps are needed to get `twin.macro` working with the default CodeSandbox React template?

What I tried was:
1. Fork the React [template](https://codesandbox.io/s/react-new)
2. Install `twin.macro` and `tailwindcss` as dependencies
3. Add an empty file called `empty.js` in the project root as described here https://github.com/ben-rogerson/twin.macro/issues/9#issuecomment-593142991, and refresh the page
4. It gets stuck forever on `Transpiling Modules...`

**Comment by ben-rogerson** [comment]
I remember adding that strange `empty.js` file in CodeSandbox too.
Btw none of that nonsense since moving [the default twin example](https://stackblitz.com/github/ben-rogerson/twin.examples/tree/master/webpack-emotion-typescript?file=src/App.tsx) to StackBlitz 🤌

In CodeSandbox the default template uses `react-scripts` aka `create-react-app` so check out either [emotion setup instructions.](https://github.com/ben-rogerson/twin.examples/tree/master/cra-emotion) or [styled-components setup instructions.](https://github.com/ben-rogerson/twin.examples/tree/master/cra-styled-components).
